var days = {
    1: {
        'date': '1.03.2016',
        'name': 'Jaskółka',
        'description': 'Początek wezwań wiosny.',
        'mission': '',
    },
    9: {
        'date': '9.03.2016',
        'name': 'Wiosenny Nowy Rok',
        'description': 'Modły o urodzaj, przewidywania pogody na lato.',
        'mission': '',
    },
    13: {
        'date': '13 - 20 marca',
        'name': 'Wiosenny Tydzień Jaryły',
        'description': 'Modły do Jaryły, śpiewanie pieśni pochwalnych.',
        'mission': '',
    },
    16: {
        'date': '16.03.2016',
        'name': 'Wierzbica, Pasieka Wiosenna',
        'description': 'Chłostanie gałązką wierzby. Oświęcenie pasieki, modły o pszczoły.',
        'mission': '',
    }, 
    18: {
        'date': '17/18 marca',
        'name': 'Wiosenne Zrównanie Dnia z Nocą - Święto Dadźboga',
        'description': 'Modły do Dadźboga, korowody dziewcząt.',
        'mission': '',
    }, 
    20: {
        'date': '20.03.2016',
        'name': 'Nawski Wielki Dzień',
        'description': 'Na ziemie przybywają dusze zmarłych - nawie. Przed wschodem słońca ludzie kąpią się w rzekach lub symbolicznie oblewają wodą.',
        'mission': '',
    }, 
    25: {
        'date': '25.03.2016',
        'name': 'Święto wiosny',
        'description': 'Rozpalanie ognisk i skakanie przezeń celem oczyszczenia, wrzucanie do rzek ofiar z chleba.',
        'mission': '',
    }, 
    26: {
        'date': '26.03.2016',
        'name': 'Wielkie Święto Peruna',
        'description': 'Oświęcenie ziarna, rozpoczęcie zasiewów. Oczekiwanie na pierwszą wiosenną burzę.',
        'mission': '',
    }, 
    41: {
        'date': '11.04.2016',
        'name': 'Wodnik Wiosenny',
        'description': 'Składanie ofiar wodnikom, by nie zatapiały ludzkich siedzib.',
        'mission': '',
    }, 
    45: {
        'date': '15.04.2016',
        'name': 'Święto Jarowita',
        'description': 'Tańce, pieśni, radowanie się i weselenie, zabawa, rytualne tarzanie się po ziemi.',
        'mission': '',
    }, 
    52: {
        'date': '22.04.2016',
        'name': 'Wielka Mokosz',
        'description': 'Święto dziewcząt - składanie ofiar z białych kogutów.',
        'mission': '',
    }, 
    53: {
        'date': '23.04.2016',
        'name': 'Święto Jaryły',
        'description': 'Święto mężczyzn - składanie ofiar z kogutów, palenie ognisk i spryskiwanie ich rytualnym piwem..',
        'mission': '',
    }, 
    60: {
        'date': '30 kwietnia/1 maja',
        'name': 'Święto Welesa',
        'description': 'Składanie ofiar Welesowi, wypędzanie bydła na pastwiska.',
        'mission': '',
    }, 
    62: {
        'date': '2 - 11 maja',
        'name': 'Tydzień Rusalny – Rusalia',
        'description': 'Kobiety składają ofiary dla rusałek - kawałki plótna oraz wianki.',
        'mission': '',
    }, 
    71: {
        'date': '11.05.2016',
        'name': 'Zielnik',
        'description': 'Zbiory ziół leczniczych, rytualne spożywanie posiłków w lasach i na polach.',
        'mission': '',
    }, 
    106: {
        'date': '15.06.2016',
        'name': 'Świętowit Letni',
        'description': 'Wznoszenie modłów do Świętowita o obfite plony.',
        'mission': '',
    }, 
    111: {
        'date': '20/21 czerwca',
        'name': 'Noc Kupały',
        'description': 'Pierwszy dzień lata. Święto obchodzone ku czci ognia. Zabawy w lasach i nad rzekami, skakanie przez ogień, puszczanie wianków na wodę, poszukiwanie kwiatu paproci. Łączenie się w pary, szczęśliwy czas poczynania dzieci.',
                                                                                                                                                                                                                                                                                                 'mission': '',
    }, 
    112: {
        'date': '21.06.2016',
        'name': 'Święto Siemargła',
        'description': 'Modły do Siemargła, składanie ofiar.',
        'mission': '',
    }, 
    120: {
        'date': '29.06.2016',
        'name': 'Wodnik Letni',
        'description': 'Składanie ofiar wodnikom z pierwszej złowionej ryby, tytoniu i piwa.',
        'mission': '',
    }, 
    121: {
        'date': '30.06.2016',
        'name': 'Pogrzeb Jaryły',
        'description': 'Spalanie kukły Jaryły.',
        'mission': '',
    }, 
    123: {
        'date': '1.07.2016',
        'name': 'Święto Swaroga - Święto Kowali',
        'description': 'Czczenie Swaroga jako boga kowalstwa, początek Sianokosów.',
        'mission': '',
    }, 
    127: {
        'date': '4/5 lipca',
        'name': 'Letnie Święto Miesiąca',
        'description': 'Modły do Chorsa, personifikacji księżyca.',
        'mission': '',
    }, 
    141: {
        'date': '20-27 lipca',
        'name': 'Perunowy Tydzień',
        'description': 'Wznoszenie modłów do Peruna, świętowanie w dębowych gajach, składanie ofiar z wieprzowiny, wołowiny, kogutów.',
        'mission': '',
    }, 
    143: {
        'date': '22.07.2016',
        'name': 'Perunica Letnia',
        'description': 'Czczenie Błyskawicy. Tego dnia nie należało pracować w polu, by nie ściągać na siebie jej gniewu.',
        'mission': '',
    }, 
    158: {
        'date': '6.08.2016',
        'name': 'Spas Jabłkowy',
        'description': 'Święcenie i spożywanie jabłek, gruszek i innych darów sadu.',
        'mission': '',
    }, 
    168: {
        'date': '16.08.2016',
        'name': 'Spas Chlebowy',
        'description': 'Święcenie i spożywanie chleba z nowego ziarna, okazywanie wdzięczności bogom za urodzaj.',
        'mission': '',
    }, 
    169: {
        'date': '16.08.2016',
        'name': 'Święto Leszego',
        'description': 'Oddawanie czci Leszemu, składanie ofiary z chleba na polanach w lasach.',
        'mission': '',
    }, 
    172: {
        'date': '19.08.2016',
        'name': 'Letni Strzybóg',
        'description': 'Czczenie Strzyboga, obserwowanie wiatrów i wróżenie z ich kierunków.',
        'mission': '',
    }, 
    187: {
        'date': '4.09.2016',
        'name': 'Perunica Jesienna',
        'description': 'Święto na cześć błyskawicy i gromu, które na zimę zasypiają. Palenie ognisk z gałęzi tarniny.',
        'mission': '',
    }, 
    191: {
        'date': '8-9 września',
        'name': 'Rodzanice - początek babiego lata',
        'description': 'Modły kobiet o dobry połóg, zdrowie niemowląt i całej rodziny.',
        'mission': '',
    }, 
    203: {
        'date': '20.09.2016',
        'name': 'Jesienny Strzybóg',
        'description': 'Modły do Strzyboga o dobrą pogodę, prognozowanie pogody na jesień z kierunków wiatrów.',
        'mission': '',
    }, 
    206: {
        'date': '23.09.2016',
        'name': 'Święto plonów',
        'description': 'Pierwszy dzień jesieni. Święto plonów, poświęcone tegorocznym zbiorom.',
        'mission': '',
    }, 
    207: {
        'date': '24.09.2016',
        'name': 'Święto Domowika i Owinnika',
        'description': 'Składanie ofiar Domowikowi i Owinnikowi - z koguta oraz miseczek napełnionych owsianką.',
        'mission': '',
    }, 
    209: {
        'date': '26.09.2016',
        'name': 'Świętowid Jesienny',
        'description': 'Święto urodzaju. Modły w chromie Świętowita, składanie ofiar, wróżby z obrzędowego napoju o przyszłej zimie.',
        'mission': '',
    }, 
    210: {
        'date': '27.09.2016',
        'name': 'Pasieka',
        'description': 'Święto pszczelarzy.',
        'mission': '',
    }, 
    214: {
        'date': '1.10.2016',
        'name': 'Jesienne Święto Matki Ziemi',
        'description': 'Początek jesienno-zimowych robót. Okres wyprawiania wesel.',
        'mission': '',
    }, 
    238: {
        'date': '25.10.2016',
        'name': 'Dziady',
        'description': 'Dzień wspominania przodków. "Dziady" odwiedzają swoje rodzinne domy, zostają ugoszczone gorącym, parującym posiłkiem.',
        'mission': '',
    }, 
    244: {
        'date': '31.10.2016',
        'name': 'Święto Mokoszy',
        'description': 'Kobiety oddają cześć Mokoszy. Ofiarują jej przędziwo i płótno.',
        'mission': '',
    }, 
    252: {
        'date': '8.11.2016',
        'name': 'Tury',
        'description': 'Święto myśliwych i początek sezonu polowań. Myśliwi składają ofiary i wznoszą modły o dobre polowania.',
        'mission': '',
    }, 
    268: {
        'date': '24.11.2016',
        'name': 'Święto Doli',
        'description': 'Wróżby.',
        'mission': '',
    }, 
    280: {
        'date': '6.12.2016',
        'name': 'Spas Zimowy',
        'description': 'Dzień nadejścia zimy.',
        'mission': '',
    }, 
    295: {
        'date': '21-23 grudnia',
        'name': 'Zimowe Staniesłońca',
        'description': 'Czczenie Swaroga, uroczyste spożywanie świętej wieczerzy.',
        'mission': '',
    }, 
    297: {
        'date': '23.12.2016',
        'name': 'Święto Roda',
        'description': 'Wygłaszanie zamówień ku czci Roda i Rodzanic, wypiekanie dla nich ciast, warzenie piwa i miodu.',
        'mission': '',
    }, 
    338: {
        'date': '2.02.2016',
        'name': 'Gromnica',
        'description': 'Zima spotyka się z wiosną. Modły do słońca - Swaroga, czczenie wszystkich bogów.',
        'mission': '',
    }, 
    345: {
        'date': '9-15 lutego',
        'name': 'Welesowy Tydzień',
        'description': 'Czczenie Welesa, wywracanie kożuchów futrem na wierzch.',
        'mission': '',
    }, 
    357: {
        'date': '21.02.2016',
        'name': 'Wiosenny Strzybóg',
        'description': 'Odprawianie modłów do boga wiatrów, przewidywanie pogody na wiosnę i lato.',
            'mission': '',
    }, 
    365: {
        'date': '26.02.2016',
        'name': 'Nowolecie',
        'description': 'Wiosenny Nowy Rok.',
        'mission': '',
    }
}
